language: node_js
node_js:
- node
cache:
  yarn: true
install:
- yarn install
script:
- yarn clean && yarn format && yarn lint && yarn test
before_deploy:
- yarn build
deploy:
  provider: npm
  email: youyou89325@163.com
  api_key:
    secure: fj6s2QpqvislvZvbDDysO1L3nWK7YO2wBBIqSKzFIstba10wBobqnV8OJE14M0/Jq/tNm9b+6IkNHylhcUxyG9dUjHIne58EGpUwhtqTbfKCAyTaB4GBMj/K760beZhZ0ubo/B06zR8rV43kA2OTXRmonQkDdpO7pTolkY9tYHCi07CNv4+P3vP45yvJLkTvPyvg0yNdKqeTB2g5iQpMExdmao2p6Ui4HmjzbWEtQ+NxHtFmTJ+NDZ3oGexXbxaWWmFc9POOsHN06Z1HI6Bpxnji2/Aum2vCwoHPC7J0iXd7zCg3lnK6YOhtOxJ/h6vbkUKQEVQSj44K4DuhRzkFuj3lMAML30sFjFdMC5l3HvQwF7zw9AFZVzVzMBojw7y0wF9Ntw85AAZu/htGsYBZSZIPt7K0sL2arTkrGm9CJfFslGoUH1+Eli5Q5883NsUIQ3EHTpsqqAoe2Iv9VHIsD/tt5rzD7q//vcHujpP73HVreWr75p76DeocC7XRS2kSW6ia0Qcz8b6na2jUD7JVrqFvMUmBChUPZdd/jQFO/6KqqgcqikmNVypH9fwi9qdUZQmm+A4yN/kid3NyFBCiaOWMOtUOyNX0E1hfKHa9PL7sceNWpylchrxzux1tcmrTTGp6hLlIpU+ScrDBI+V4wwWKOjiWtUcMpRMHVqC4+jw=
  on:
    repo: YouChunMing/ycm-cloud-music-redux
branches: master
env:
  global:
    secure: ObQAJEGrJI/UgI8xcYf2s9FqS90jUxgcLzOWxzzIRSP5JVZrcKhDnuM09nOkwAoKd2BBNVYGdWmaQ0gvCZFjczsQLnpRpdryVIUEmCymIwyUQ1OFLTRElCpkvJv2e1Q8dcpnpqeO55A915Zk6S6GqjnSQVwOwOC44eo4/jCgY8bL9lO1AMAElEutanwDH4I97WciYVMmgOQeGxlRF4OMaBzXacAzhWWEIKjoFIUMp3UnLHfzyaGcPug79Tptaw5fZxjPMK5DTNcwqXkcmRPunZWA0cjrWNYAS7J1KDe4otiadaID6X3H4DkalRqph9LgrkezZ8OLTQqa33mvUAQfOuZrTNLrYt1HhvzGfTb9THIqz5ovsKSbAxHKq95mgQ3HMJHUbvgtexxhmfwhFeBjceM2KZAH2BrcjxptpA63GyWCr40Xb6GrVQd3EjHXsnH2vQ/O9gduLy8qiq1Pmeg/OIMa2WHV/fsGBG9kGr+ReGo9sRnOD3UwkdP6vF8d8fpKeZtjymAXbBZegoMiULHXm1wAdxFhmJtbF0Y9K7QxTh34bX/tHuZ5FdWrhILbz/HALkg+bTHEqhNlaDk6LOTu9EE0XNn6vSKfu6J9afysGSlyDxH+Gna6Os4OgCiudF68M4O/uIIhmIOOiy5smlV1mvyv3D7WAK6eKgDkiDVDH3I=
