language: node_js
node_js:
- node
cache:
  yarn: true
install:
- yarn install
script:
- yarn clean && yarn format && yarn lint && yarn test
before_deploy:
- yarn build
deploy:
  edge: true
  cleanup: false
  provider: npm
  email: youyou89325@163.com
  api_token: $API_TOKEN
branches: master
